config/routes.rb
Swingin::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  resources :users

  root :to => 'users#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  attr_accessible :img_url, :start_date, :end_date

  validates :img_url, :start_date, :end_date, presence: true

  validates :img_url, format: { with: %r{\.(gif|jpe?g|png)$}i,
    message: 'Must have a valid image extension' }

  validates :start_date,
    date: { after: Proc.new { Date.today - 1 },
      message: "Must be on or after today's date" }

  validates :end_date,
    date: { after: :start_date, message: "Must be after start's date" }
end

app/models/advertiser.rb
# coding: utf-8
class Advertiser < ActiveRecord::Base
  attr_accessible :address, :city, :company, :email, :mobile_number,
    :phone_number, :postal_code, :state, :website_url

  validates :address, :city, :company, :email, :mobile_number, :phone_number,
    :postal_code, :state, presence: true

  validates :city, :state, format: { with: /[a-zA-Z\s]+/ }

  validates :email, format: { with: /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i }

  validates :postal_code, format:  { with: /^\d{6}/ }

  validates :phone_number, :mobile_number, phony_plausible: true

  validates :website_url, url: { allow_blank: true }

  phony_normalize :phone_number, default_country_code: 'IN'
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  attr_accessible :coupon_code

  validates :coupon_code, uniqueness: true

  validates :coupon_code, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

    # Override build_footer method in ActiveAdmin::Views::Pages
  require 'active_admin_views_pages_base.rb'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :html, :xml, :json
	inherit_resources
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swingin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Balthazar' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class = 'social-icons'>
    <div class = 'facebook-icon label label-default'>
        <i class="fa fa-facebook fa-3"></i> facebook
    </div>
  </div>
  <div class="container-fluid menu">
    <div class="navbar navbar-default margin noBottom " role="navigation">
      <a class="brand img-responsive pull-right" href="#">
        Swing IN
      </a>

      <div class="navbar-inner menu" >
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse">
            <ul class="nav navbar-nav menuitem pull-right">
              <li><%= link_to root_path do %>
                <i class="fa fa-home"></i><br>Home
                <%end%>
              </li>
              <li><%= link_to page_path('how_app_works') do %>
                <i class="fa fa-road"></i> <br>How App Works
                <%end%>
              </li>
              <li><%= link_to page_path('advertisers') do %>
                <i class = "fa fa-smile-o" ></i><br>Advertisers
                <%end%>
              </li>
              <li><%= link_to page_path('contact') do%>
                <i class="fa fa-envelope-o"></i><br>Contact Us
                <%end%>
              </li>
              <li><%= link_to page_path('about') do %>
                <i class = "fa fa-info" ></i><br>About
                <%end%>
              </li>
            </ul>
          </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <%= yield %>
    <div class="footer bottom">
      <div class = "span2">
        <p>&copy; 2013 
          <%= link_to 'Swing IN' %>
        </p>
      </div>
       <div class = "span6 footer-links">
          <%= link_to 'home', root_path %> |
          <%= link_to 'advertisers', page_path('advertisers') %> |
          <%= link_to 'contact us', page_path('contact') %> |
          <%= link_to 'about the app', page_path('about') %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/about.haml
%div.row-fluid.border.text-color-violet
  %div.span6.main
    %div.greeting.span12
      Hello! नमस्ते!
    %div.info.span6
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/pages/advertisers.haml
%div.row-fluid.border.text-color-violet
  %div.span6.main
    %div.greeting.span12
      Hello! नमस्ते!
    %div.info.span6
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/pages/contact.haml
%div.row-fluid.border.text-color-violet
  %div.span6.main
    %div.header-label.well.well-large
      Contact Us
    = form_for :user, html: { class: 'form-horizontal' } do |f|
      %div.control-group
        = f.label :name, 'Name', class: 'control-label'
        %div.controls
          = f.text_field :name
      %div.control-group
        = f.label :email, class: 'control-label'
        %div.controls
          = f.text_field :email
      %div.control-group
        = f.label :message, class: 'control-label'
        %div.controls
          = f.text_area :address, rows: 3
      %div.control-group
        %div.controls
          = f.submit 'Submit', class: 'btn btn-primary'

app/views/pages/how_app_works.haml
%div.row-fluid.border.text-color-violet
  %div.span6.main
    %div.greeting.span12
      Hello! नमस्ते!
    %div.info.span6
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/users/index.haml
%div.row-fluid.border
  %div.span9.main
    %p.text-info.text-color-violet
      %div.admin_link
        = link_to 'Admin Login', new_admin_user_session_path
        %br
        %br
        Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis.

        Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit ame

        %br
        %br
        = link_to 'Download App from Play store', '#', class: 'playstore-link'
        %br
        = link_to "#", class: 'playstore-img-link' do
          = image_tag "/assets/playstore.png"
  %div.span3
    %img.media-object{ :src => "assets/rankpage.png" }

app/views/users/new.haml
= form_for :user, url: users_path do |f|
  Email:
  = f.email_field :email
  %br
  Password:
  = f.password_field :password
  %br
  Confirm Password:
  = f.password_field :confirm_password
  %br
  Date of Birth:
  = f.date_select :date_of_birth
  %br
  Gender:
  = f.select :gender_type, options_for_select([["Select One", ""], "Male", "Female"])

  = f.submit

app/views/users/show.haml
%span
   = resource.email
   has been successfully registered.